name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código
        uses: actions/checkout@v4
      - name: Rodar os testes
        run: echo "Testes do CI aprovados com sucesso!"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Simular Deploy
        run: echo "Deploy executado com sucesso!"
