name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código
        uses: actions/checkout@v4
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Rodar o script
        run: node script.js

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Simular Deploy
        run: echo "Deploy executado com sucesso!"
