name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código
        uses: actions/checkout@v4
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Instalar dependências
        run: npm install
      - name: Rodar testes unitários
        run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Simular Deploy
        run: echo "Deploy executado com sucesso!"
      - name: Notificar Discord
        uses: sarisia/actions-status-discord@v1
        if: always() # Garante que envia alerta mesmo se o teste falhar
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          content: "Opa Daniel! O Workflow do Zé da Manga acabou de rodar."
          title: "Status do Build"
